In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.linear_model import LinearRegression
import statsmodels.api as sm

# Import dữ liệu

In [3]:
data = pd.read_csv('air_condition_2021.csv')
data = data[['AQI index', 'Dominent pollutant', 'PM10', 'PM2.5']]
data

AQI index Dominent pollutant  PM10  PM2.5
0            36               pm25    29   36.0
1            68               pm25    52   68.0
2           217               pm25   194  217.0
3           195               pm25   119  195.0
4           168               pm25    65  168.0
...         ...                ...   ...    ...
1749         59               pm25    33   59.0
1750        168               pm25   126  168.0
1751        162               pm25   108  162.0
1752        149               pm25    76  149.0
1753        114               pm10   114   77.0

[1754 rows x 4 columns]

## Tính giá trị các hàm log cho các biến độc lập PM10 và PM2.5

In [4]:
data['log10(1/PM10)'] = np.log10(1/data['PM10'])
data['log10(1/PM2.5)'] = np.log10(1/data['PM2.5'])
data

AQI index Dominent pollutant  PM10  PM2.5  log10(1/PM10)  log10(1/PM2.5)
0            36               pm25    29   36.0      -1.462398       -1.556303
1            68               pm25    52   68.0      -1.716003       -1.832509
2           217               pm25   194  217.0      -2.287802       -2.336460
3           195               pm25   119  195.0      -2.075547       -2.290035
4           168               pm25    65  168.0      -1.812913       -2.225309
...         ...                ...   ...    ...            ...             ...
1749         59               pm25    33   59.0      -1.518514       -1.770852
1750        168               pm25   126  168.0      -2.100371       -2.225309
1751        162               pm25   108  162.0      -2.033424       -2.209515
1752        149               pm25    76  149.0      -1.880814       -2.173186
1753        114               pm10   114   77.0      -2.056905       -1.886491

[1754 rows x 6 columns]

# Lấy ra giá trị X tương ứng với log10(1/PM10) và log10(1/PM2.5) - y tương ứng với AQI index

In [6]:
X, y = np.array(data[['log10(1/PM10)', 'log10(1/PM2.5)']]).reshape((-1, 2)), np.array(data[['AQI index']]).reshape((-1, 1))

In [7]:
X

array([[-1.462398  , -1.5563025 ],
       [-1.71600334, -1.83250891],
       [-2.28780173, -2.33645973],
       ...,
       [-2.03342376, -2.20951501],
       [-1.88081359, -2.17318627],
       [-2.05690485, -1.88649073]])

In [8]:
y

array([[ 36],
       [ 68],
       [217],
       ...,
       [162],
       [149],
       [114]], dtype=int64)

# Sử dụng công thức Coefficient = (XT * X)-1 * XT * Y

In [22]:
vector = np.ones((len(X), 1))
X_1 = np.concatenate((X, vector), axis=1)
xT = X_1.transpose()
xTx = np.dot(xT, X_1)
xTx_inv = np.linalg.inv(xTx)
xTx_inv_xT = np.dot(xTx_inv, xT)
final = np.dot(xTx_inv_xT, y)

In [23]:
final

array([[-12.67694445],
       [-64.81510079],
       [-59.70362947]])

# Tạo mô hình hồi quy tuyến tính từ thư viện sklearn

In [9]:
model = LinearRegression()
model.fit(X, y)

LinearRegression()

# Tính toán Intercept, Coefficient và R Square để đánh giá mô hình hồi quy

In [10]:
print(f"Intercept: {model.intercept_}")
print(f"Coefficient: {model.coef_}")
print(f"R Square: {model.score(X, y)}")

Intercept: [-59.70362947]
Coefficient: [[-12.67694445 -64.81510079]]
R Square: 0.6322689773330288
